# Import Data + Librar

In [298]:
import pandas as pd
import numpy as np

In [299]:
data = pd.read_csv("/Users/lolok/Desktop/CountryData.csv")
X1 = data.iloc[:, 1:8].values
X2 = data.iloc[:, 9:].values
X = np.concatenate((X1,X2),axis = 1)
y = data.iloc[:, 8].values
data

Country                               Region  Population  \
0       Afghanistan         ASIA (EX. NEAR EAST)             31056997   
1           Albania   EASTERN EUROPE                          3581655   
2           Algeria   NORTHERN AFRICA                        32930091   
3    American Samoa   OCEANIA                                   57794   
4           Andorra   WESTERN EUROPE                            71201   
..               ...                                  ...         ...   
222       West Bank   NEAR EAST                               2460492   
223  Western Sahara   NORTHERN AFRICA                          273008   
224           Yemen   NEAR EAST                              21456188   
225          Zambia   SUB-SAHARAN AFRICA                     11502010   
226        Zimbabwe   SUB-SAHARAN AFRICA                     12236805   

        Area  Pop. Density  Coastline  Net migration  Infant mortality  \
0     647500          48.0       0.00          23.06            163.07   
1      28748         124.6       1.26          -4.93             21.52   
2    2381740          13.8       0.04          -0.39             31.00   
3        199         290.4      58.29         -20.71              9.27   
4        468         152.1       0.00           6.60              4.05   
..       ...           ...        ...            ...               ...   
222     5860         419.9       0.00           2.98             19.62   
223   266000           1.0       0.42            NaN               NaN   
224   527970          40.6       0.36           0.00             61.50   
225   752614          15.3       0.00           0.00             88.29   
226   390580          31.3       0.00           0.00             67.69   

         GDP  Literacy  Phones  Arable  Crops  Other  Climate  Birthrate  \
0      700.0      36.0     3.2   12.13   0.22  87.65      1.0      46.60   
1     4500.0      86.5    71.2   21.09   4.42  74.49      3.0      15.11   
2     6000.0      70.0    78.1    3.22   0.25  96.53      1.0      17.14   
3     8000.0      97.0   259.5   10.00  15.00  75.00      2.0      22.46   
4    19000.0     100.0   497.2    2.22   0.00  97.78      3.0       8.71   
..       ...       ...     ...     ...    ...    ...      ...        ...   
222    800.0       NaN   145.2   16.90  18.97  64.13      3.0      31.67   
223      NaN       NaN     NaN    0.02   0.00  99.98      1.0        NaN   
224    800.0      50.2    37.2    2.78   0.24  96.98      1.0      42.89   
225    800.0      80.6     8.2    7.08   0.03  92.90      2.0      41.00   
226   1900.0      90.7    26.8    8.32   0.34  91.34      2.0      28.01   

     Deathrate  Agriculture  Industry  Service  
0        20.34        0.380     0.240    0.380  
1         5.22        0.232     0.188    0.579  
2         4.61        0.101     0.600    0.298  
3         3.27          NaN       NaN      NaN  
4         6.25          NaN       NaN      NaN  
..         ...          ...       ...      ...  
222       3.92        0.090     0.280    0.630  
223        NaN          NaN       NaN    0.400  
224       8.30        0.135     0.472    0.393  
225      19.93        0.220     0.290    0.489  
226      21.84        0.179     0.243    0.579  

[227 rows x 20 columns]

# Fix Missing Values

In [300]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:])
X[:, 1:] = imputer.transform(X[:,1:])

# Encode Independent + Dependent Variables

In [301]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [302]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

# Split into Test and Train set

In [303]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.01, random_state = 1)

In [304]:
print(X_train)
print()
print(X_test)
print()
print(y_train)
print()
print(y_test)
print()

[[0.0 0.0 0.0 ... 0.03 0.906 0.062]
 [0.0 0.0 0.0 ... 0.249 0.23 0.519]
 [0.0 0.0 0.0 ... 0.025 0.303 0.671]
 ...
 [0.0 0.0 0.0 ... 0.061 0.592 0.348]
 [0.0 0.0 0.0 ... 0.15084433962264152 0.28271090047393366
  0.5652830188679244]
 [0.0 0.0 0.0 ... 0.121 0.219 0.66]]

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 4303356.0 622984.0 6.9 0.0
  0.0 91.0 51.0 2.3 3.1 0.14 96.76 2.0 33.91 18.65 0.55 0.2 0.25]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 22303552.0 237500.0 93.9
  0.09 -0.13 26.43 98.4 196.9 40.82 2.25 56.93 3.0 10.7 11.77 0.101 0.35
  0.549]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 299388.0 103000.0 2.9 4.83
  2.38 3.31 99.9 647.7 0.07 0.0 99.93 3.0 13.64 6.72 0.086 0.15 0.765]]

[ 22  26  68 126  95  33  11  93  35  31  25  98   5   6  47  44  30  99
  14  91   8   2   4 101  87  46  70  81  13   3 118  32 116   1  23  13
 117  92   2  12  44  64  97  83  14  20  49  12   0  93  39  88  17  54
   3   7   0 111  14  17  72  41  36  49  31  26  11   5  23  66  84   6
 

# Feature Scale Data

In [306]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 13:] = sc.fit_transform(X_train[:, 13:])
X_test[:,13:] = sc.transform(X_test[:, 13:])

# Create Multiple Linear Regression Model

In [307]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

# Predict Data

In [308]:
y_pred = regressor.predict(X_test)
y_pred

array([  4.80162811,  54.71682067, 107.69262909])

# Assess Accuracy

In [309]:
regressor.score(X_test, y_test)

0.9678464506249231